### PR TITLE
Implementing Docker & Update Service Host to AWS EC2

### PR DESCRIPTION
**Pull request by Nitzantomer1998**
To improve durability, we are transitioning the deployment from Render to AWS EC2 while also utilizing Docker. This change will offer several benefits:

1. Enhanced Stability: AWS EC2 provides a robust and scalable infrastructure, ensuring high availability and minimizing downtime.
2. Isolation and Consistency: Using Docker allows us to containerize the application, ensuring consistent performance across different environments and simplifying the deployment process.
3. Scalability: AWS EC2 makes it easier to scale resources up or down based on demand, providing flexibility to handle varying workloads.
4. Resource Management: Docker's lightweight containers allow for efficient resource management, optimizing the use of CPU, memory, and storage.

By combining AWS EC2's powerful infrastructure with Docker's containerization capabilities, we can achieve a more reliable and efficient deployment.

### CODE REVIEW

**Comment by TwilightMercy** [comment]
Is the addon down?

https://stremio-wizdom-addon-mcty.onrender.com/configure

image


image

**Comment by Nitzantomer1998** [comment]
As we discussed regarding the hosting service situation, my service will be down due to the limitations of the free tier.

I have now migrated my hosting server from **Render** to **AWS EC2**, so the link has been updated.

I followed instructions from a developer at Stremio, which should update the addon URL for all users. The old version should automatically update to the new one.

Can you let me know where you found my addon? I will reach out to the relevant parties to ensure the URL is updated in their system.

**Comment by TwilightMercy** [comment]
Here :)

https://stremio-addons.netlify.app/universal-hebrew-subtitles

**Comment by TwilightMercy** [comment]
Also, the link in "About" section 
https://github.com/Nitzantomer1998/UniversalHebrewSubtitles
refers to:
https://ec2-18-196-63-110.eu-central-1.compute.amazonaws.com/

image

Instead of:
https://ec2-18-196-63-110.eu-central-1.compute.amazonaws.com/configure

**Comment by Nitzantomer1998** [comment]
Honestly, I intentionally directed users to the base URL instead of the configure page. If it goes to the configure page, it increments my addon counter by 1, which isn't necessarily accurate in terms of installs.

I'll considering changing it to the configure page, as it might be the right move. However, this change could affect the reliability of my addon tracker.

Regarding the Description and ReadMe, I haven't had the chance to focus on those yet.

I prioritized fixing more important things such as bugs, resilience, performance improvements, and determining the perfect hosting service.

**Pull request merged**
